# NB02 - Create Embeddings

## Import dependencies

In [1]:
# General libraries
import sys
import os
import json
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
tqdm.pandas()

# Hugging Face Transformers
from transformers import AutoTokenizer, AutoModel

# Scikit-learn metrics
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances

# Add the project root to Python path (assuming current working directory is 'notebooks')
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Own functions
from utils import get_mean_embeddings, populate_doc_chunks_from_dict, populate_doc_chunks_from_json, count_chunks_for_doc, bulk_process_and_store_chunks, get_embeddings_from_json
from climate_policy_extractor.models import DocChunk, get_db_session
from sqlalchemy import create_engine, text, func

db_url = os.getenv('DATABASE_URL')

Download/Load embedding models

In [2]:
# Load ClimateBERT tokenizer and model
model_name = 'climatebert/distilroberta-base-climate-f'
local_model_save = '../local_models/climatebert/distilroberta-base-climate-f'

# # Uncomment to download model
# tokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=False)
# model = AutoModelForMaskedLM.from_pretrained(model_name, use_auth_token=False)

# # Save it to a local_models folder
# tokenizer.save_pretrained(local_model_save)
# model.save_pretrained(local_model_save)

# Load the models from disk
tokenizer = AutoTokenizer.from_pretrained(local_model_save)
model = AutoModel.from_pretrained(local_model_save)

Some weights of the model checkpoint at ../local_models/climatebert/distilroberta-base-climate-f were not used when initializing RobertaModel: ['lm_head.bias', 'lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at ../local_models/climatebert/distilroberta-base-climate-f and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [3]:
# Run this if you want to load all chunks
all_chunks = json.load(open('../data/json/all_chunks_bert.json', 'r'))
all_chunks.keys()

# # Run this if you want to load a few chunks for testing
# all_chunks = json.load(open('../data/json/snippet_doc_chunks.json', 'r'))
# all_chunks.keys()

dict_keys(['afghanistan_english_20220601', 'albania_english_20220801', 'algeria_english_20220601', 'andorra_spanish_20230101', 'andorra_spanish_20250201', 'angola_english_20220601', 'antigua_and_barbuda_english_20220601', 'argentina_spanish_20220501', 'armenia_english_20220601', 'australia_english_20220601', 'azerbaijan_english_20231001', 'bahamas_english_20221101', 'bahrain_english_20220601', 'bangladesh_english_20220601', 'barbados_english_20220601', 'belarus_english_20220601', 'belize_english_20220601', 'benin_french_20220601', 'bhutan_english_20220601', 'bolivia_(plurinational_state_of)_english_20220601', 'bosnia_and_herzegovina_english_20220601', 'botswana_english_20220601', 'botswana_english_20241201', 'brazil_english_20241101', 'brunei_darussalam_english_20220601', 'burkina_faso_french_20220601', 'burundi_french_20220601', 'cabo_verde_english_20220601', 'cambodia_english_20220601', 'cameroon_french_20220601', 'canada_english_20220601', 'canada_english_20250201', 'central_african_republic_french_20220601', 'chad_french_20220601', 'chile_spanish_20220601', 'china_english_20220601', 'colombia_spanish_20220601', 'comoros_french_20220601', 'congo_french_20220601', 'cook_islands_english_20220601', 'costa_rica_spanish_20220601', 'cuba_english_20220601', 'cuba_spanish_20250201', "côte_d'ivoire_french_20220601", "democratic_people's_republic_of_korea_english_20220601", 'democratic_republic_of_the_congo_french_20220601', 'djibouti_english_20220601', 'dominican_republic_spanish_20220601', 'dominica_english_20220701', 'ecuador_spanish_20220601', 'ecuador_spanish_20250201', 'egypt_english_20230601', 'el_salvador_spanish_20220601', 'equatorial_guinea_spanish_20221001', 'eritrea_english_20220601', 'eswatini_english_20220601', 'ethiopia_english_20220601', 'fiji_english_20220601', 'gabon_french_20220701', 'gambia_english_20220601', 'georgia_english_20220601', 'ghana_english_20220601', 'grenada_english_20220601', 'guatemala_spanish_20220601', 'guinea-bissau_english_20220601', 'guinea_french_20220601', 'guyana_english_20220601', 'haiti_french_20220601', 'holy_see_english_20230501', 'honduras_spanish_20220601', 'iceland_english_20220601', 'india_english_20220801', 'indonesia_english_20220901', 'iraq_arabic_20220601', 'israel_english_20220601', 'jamaica_english_20220601', 'japan_english_20220601', 'japan_english_20250201', 'jordan_english_20220601', 'kazakhstan_english_20230601', 'kenya_english_20220601', 'kiribati_english_20230301', 'kuwait_english_20220601', 'kyrgyzstan_english_20220601', "lao_people's_democratic_republic_english_20220601", 'lebanon_english_20220601', 'lesotho_english_20250201', 'liberia_english_20220601', 'liechtenstein_english_20220601', 'madagascar_french_20240101', 'malawi_english_20220601', 'malaysia_english_20220601', 'maldives_english_20220601', 'maldives_english_20250201', 'mali_french_20220601', 'marshall_islands_english_20220601', 'marshall_islands_english_20250201', 'mauritania_french_20220601', 'mauritius_english_20220601', 'mexico_spanish_20221101', 'micronesia_(federated_states_of)_english_20221001', 'monaco_french_20220601', 'mongolia_english_20220601', 'montenegro_english_20220601', 'montenegro_english_20250201', 'morocco_french_20220601', 'mozambique_english_20220601', 'myanmar_english_20220601', 'namibia_english_20240101', 'nauru_english_20220601', 'nepal_english_20220601', 'new_zealand_english_20220601', 'new_zealand_english_20250101', 'nicaragua_spanish_20220601', 'nigeria_english_20220601', 'niger_french_20220601', 'niue_english_20220601', 'north_macedonia_english_20220601', 'norway_english_20221101', 'oman_english_20231101', 'pakistan_english_20220601', 'palau_english_20220601', 'panama_spanish_20240601', 'papua_new_guinea_english_20220601', 'paraguay_spanish_20220601', 'peru_spanish_20220601', 'philippines_english_20220601', 'qatar_english_20220601', 'republic_of_korea_english_20220601', 'republic_of_moldova_english_20220601', 'russian_federation_english_20220601', 'rwanda_english_20220601', 'saint_kitts_and_nevis_english_20220601', 'saint_lucia_english_20220601', 'saint_lucia_english_20250201', 'saint_vincent_and_the_grenadines_english_20220601', 'samoa_english_20220601', 'san_marino_english_20220601', 'sao_tome_and_principe_english_20220601', 'saudi_arabia_english_20211023', 'senegal_french_20220601', 'serbia_english_20220801', 'seychelles_english_20220601', 'sierra_leone_english_20220601', 'singapore_english_20221101', 'singapore_english_20250201', 'solomon_islands_english_20220601', 'somalia_english_20220601', 'south_africa_english_20220601', 'south_sudan_english_20220601', 'sri_lanka_english_20220601', 'state_of_palestine_english_20220601', 'sudan_english_20221001', 'suriname_english_20220601', 'switzerland_english_20241101', 'switzerland_english_20250101', 'syrian_arab_republic_english_20220601', 'tajikistan_english_20220601', 'thailand_english_20221101', 'timor-leste_english_20221101', 'togo_french_20220601', 'tonga_english_20220601', 'trinidad_and_tobago_english_20220601', 'tunisia_french_20220601', 'turkmenistan_english_20230101', 'tuvalu_english_20230201', 'türkiye_english_20230401', 'uganda_english_20220901', 'ukraine_english_20220601', 'united_arab_emirates_english_20241101', 'united_kingdom_of_great_britain_and_northern_ireland_english_20220901', 'united_kingdom_of_great_britain_and_northern_ireland_english_20250101', 'united_republic_of_tanzania_english_20220601', 'united_states_of_america_english_20220601', 'united_states_of_america_english_20241201', 'uruguay_spanish_20221201', 'uruguay_spanish_20250101', 'uzbekistan_english_20220601', 'vanuatu_english_20220801', 'venezuela_(bolivarian_republic_of)_spanish_20220601', 'viet_nam_english_20221101', 'zambia_english_20220601', 'zambia_english_20250301', 'zimbabwe_english_20220601', 'zimbabwe_english_20250201'])

In [5]:
# For multiple files
all_chunks_list = []

for doc, chunks_list in all_chunks.items():
    for chunk in chunks_list:
        # Add the filename as document ID to each chunk
        chunk = chunk.copy()  # Create a copy to avoid modifying the original
        chunk['doc_id'] = doc
        all_chunks_list.append(chunk)

# Create DataFrame from all chunks
all_chunks_df = pd.DataFrame(all_chunks_list)

# Get dims of DataFrame
all_chunks_df.head(2)

,id,type,text,page_number,metadata,doc_id
0,0,CompositeElement,ISLAMIC REPUBLIC OF AFGHANISTAN\n\nIntended Na...,1,"{'file_directory': '..\data\pdfs', 'filename':...",afghanistan_english_20220601
1,1,CompositeElement,Executive Summary\n\nBase Year:\n\n2005\n\nTar...,1,"{'file_directory': '..\data\pdfs', 'filename':...",afghanistan_english_20220601

WILL TAKE A LONG TIME FOR ALL CHUNKS

In [ ]:
all_chunks_df.loc[:, 'embedding'] = all_chunks_df['text'].progress_apply(lambda x: get_mean_embeddings(x, model, tokenizer))
all_chunks_df.to_json('../data/json/all_chunks_bert_embeddings.json', orient='records')
all_chunks_df.tail()

  0%|          | 0/65306 [00:00<?, ?it/s]

,id,type,text,page_number,metadata,doc_id,embedding
65301,302,CompositeElement,ow emissions development strategies and actions.,40,"{'file_directory': '..\data\pdfs', 'filename':...",zimbabwe_english_20250201,"[-0.0149321798235178, -0.018060462549328804, -..."
65302,303,CompositeElement,"5.2 CAPACITY\n\nBUILDING,\n\nEDUCATION,\n\nTRA...",40,"{'file_directory': '..\data\pdfs', 'filename':...",zimbabwe_english_20250201,"[0.02068692073225975, -0.09388821572065353, -0..."
65303,304,CompositeElement,The cross-cutting nature of the climate action...,40,"{'file_directory': '..\data\pdfs', 'filename':...",zimbabwe_english_20250201,"[0.017246006056666374, 0.017260683700442314, 0..."
65304,305,CompositeElement,the gender disparities,40,"{'file_directory': '..\data\pdfs', 'filename':...",zimbabwe_english_20250201,"[0.03902190178632736, 0.10949282348155975, -0...."
65305,306,CompositeElement,in\n\nthis NDC\n\ninformation and actions.\n\n...,40,"{'file_directory': '..\data\pdfs', 'filename':...",zimbabwe_english_20250201,"[0.001697609550319612, -0.01692597195506096, -..."

### Update Database with chunks and embeddings

In [ ]:
# # Load the JSON file into a DataFrame (run this if you already have the json with embeddings)
# with open('../data/json/all_chunks_bert_embeddings.json', 'r') as f:
#     all_chunks_dict = json.load(f)

# Call populate table function (run this if you are running the notebook for the first time)
all_chunks_dict = all_chunks_df.to_dict(orient='records')

all_chunks_dict[0]

{'id': 0,
 'type': 'CompositeElement',
 'text': 'ISLAMIC REPUBLIC OF AFGHANISTAN\n\nIntended Nationally Determined Contribution\n\nSubmission to the United Nations Framework Convention on Climate Change\n\n21 September 2015\n\n*****\n\nThe Islamic Republic of Afghanistan hereby communicates its Intended Nationally Determined Contribution (INDC) and information to facilitate understanding of the contribution.',
 'page_number': 1,
 'metadata': {'file_directory': '..\\data\\pdfs',
  'filename': 'afghanistan_english_20220601.pdf',
  'languages': ['eng'],
  'last_modified': '2025-03-24T10:38:04',
  'filetype': 'application/pdf'},
 'doc_id': 'afghanistan_english_20220601',
 'embedding': [0.0687589496,
  0.0500213914,
  -0.0266364403,
  0.0401619188,
  0.5135895014,
  0.1837328225,
  0.0577176176,
  0.0770772249,
  0.1838382483,
  -0.0776428133,
  -0.0614188574,
  0.357621938,
  0.000802157,
  -0.1518113464,
  0.0904157832,
  -0.2905346453,
  -0.1204291806,
  0.0422070585,
  0.1236632243,
  0.1092292666,
  -0.1464197487,
  0.1656692773,
  0.06543798,
  -0.0481665693,
  -0.0990711376,
  0.0547921509,
  -0.0128553491,
  0.0611686409,
  -0.0416584238,
  0.0022946189,
  -0.2458093613,
  0.0005075947,
  0.1182363704,
  -0.0970198363,
  -0.0256180707,
  0.0219235588,
  0.0002737015,
  0.0608962402,
  -0.0443632975,
  0.0007190704,
  0.0169100035,
  -0.389539212,
  -0.0326504707,
  -0.0102028586,
  0.0937294662,
  0.103824228,
  -0.2166782022,
  -0.090254724,
  -0.0137333572,
  -0.010937077,
  0.1537355185,
  -0.0712722614,
  -0.0455531701,
  -0.0378958136,
  -0.0335631073,
  0.1080169678,
  -0.106433928,
  0.1650221646,
  -0.0273007508,
  -0.0514847487,
  0.040031597,
  0.4699032903,
  -0.0918346494,
  0.0232144278,
  0.0179436691,
  0.0400603525,
  0.0255944338,
  -0.0945697203,
  0.0159754511,
  0.1617679745,
  -0.0228742063,
  -0.0812418312,
  0.0628912598,
  0.0610986799,
  0.0439917557,
  0.235991776,
  0.1174047962,
  -4.4651627541,
  0.0046098321,
  0.0701303929,
  -0.0415064394,
  -0.0471631922,
  1.6402659416,
  0.0619065985,
  0.1357790828,
  0.2167361826,
  -0.02311977,
  -0.2351540923,
  -0.0064452896,
  -0.0111910338,
  0.0799735039,
  0.0142820152,
  -0.0575619228,
  0.2530368268,
  0.002298733,
  -0.0078616366,
  0.0363808461,
  0.4102867246,
  -0.0236614514,
  0.0230953731,
  0.218693018,
  0.0124466885,
  0.3075779974,
  0.061799489,
  0.0225150306,
  -0.0081749894,
  -0.2313567549,
  -0.0148903597,
  0.130645752,
  0.0422365256,
  0.0996743292,
  0.1931170076,
  0.0760953128,
  0.0704442263,
  -0.0337765366,
  0.1181753501,
  0.0944119617,
  -0.0876850039,
  -0.0551673956,
  -0.0251538865,
  0.0954915434,
  0.0971363187,
  0.1114014238,
  -0.0099855019,
  0.129238829,
  0.0971623063,
  0.0724834427,
  0.150727883,
  -0.064003855,
  0.0217656605,
  0.0195095781,
  -0.365698427,
  0.0964791402,
  -0.0988759771,
  0.1235467345,
  0.0640789792,
  0.0582007021,
  0.0433245637,
  -0.036522083,
  0.0327462256,
  -0.015047295,
  0.0889393166,
  -0.1103119552,
  -0.0539389253,
  0.1005933136,
  -0.0325652473,
  -0.0909375995,
  -0.1961177438,
  0.0828123093,
  0.1680661887,
  0.0154254148,
  0.0133638186,
  -0.034234114,
  0.1282379478,
  -0.039192494,
  0.1130028591,
  -0.1320309043,
  0.1182647645,
  0.0795694292,
  0.3999633193,
  0.214397192,
  0.2623043358,
  -0.1508873999,
  -0.0354154445,
  -0.0429709293,
  0.0288469102,
  0.0830941647,
  0.1449669003,
  -0.0903779268,
  0.2818688154,
  -0.1274967343,
  0.0464161858,
  -0.1111267284,
  -0.0143329753,
  -0.0363073349,
  -0.0008294085,
  0.1029232517,
  0.0228909645,
  -0.0641813874,
  -0.1653833985,
  0.0269293785,
  0.0576307736,
  0.0336902365,
  -0.0798199922,
  0.021708522,
  0.0855563655,
  -0.0709317699,
  0.0818725377,
  0.1938645989,
  -0.0906290039,
  0.1309348792,
  -0.0275175571,
  0.038640555,
  0.266557157,
  0.1440656334,
  0.2437549829,
  0.1219660938,
  0.0538208522,
  0.1297211349,
  0.053817682,
  -0.1673135906,
  -0.0696433857,
  0.1044668257,
  0.0317403413,
  0.1937120706,
  0.1226637736,
  -0.0024379054,
  0.1237751469,
  -0.0778055042,
  0.0281882286,
  -0.0546776615,
  -0.1060342938,
  -0.054905422,
  0.1688645333,
  -0.1347131431,
  -0.0352996737,
  0.0757435039,
  -0.7083160281,
  -0.0782342628,
  -0.4308219254,
  0.0444635302,
  0.0741615519,
  0.3273418546,
  -0.1033164784,
  0.3187299371,
  0.15586932,
  0.1196423024,
  -0.0470286906,
  0.0095273182,
  -0.0856957287,
  0.0817062259,
  -0.0960628614,
  -0.155236274,
  -0.0970417485,
  -0.0219674911,
  0.175246492,
  0.0617252663,
  0.0546463355,
  0.057449203,
  0.077298969,
  0.1138018966,
  0.0589625984,
  0.0767049864,
  0.1034285128,
  -0.0051115812,
  0.2116500735,
  -0.059954714,
  0.4018480182,
  0.1781739295,
  0.2072339803,
  0.0388507359,
  -0.0893211141,
  0.0346519165,
  -0.1061534286,
  -0.1591623724,
  0.095048666,
  -0.0107578151,
  -0.1790638864,
  -0.0372988544,
  -0.2966607511,
  -0.0214763768,
  -0.0232858174,
  0.2196011096,
  -0.0286219902,
  -0.0171146709,
  -0.1334721595,
  -0.0611228384,
  0.0762948617,
  0.0958389416,
  -0.1363813728,
  0.0886793807,
  0.0366006941,
  -0.0312527157,
  -0.1140542105,
  0.0503282547,
  0.0710632801,
  -0.1046896428,
  0.0352215357,
  0.1596192718,
  -0.0073226043,
  0.0446254686,
  0.061391376,
  -0.2364519536,
  -0.1006478891,
  -0.06819693,
  0.043156147,
  -0.3211527765,
  -0.1196866557,
  -0.0562198721,
  0.0755652413,
  0.1189642698,
  0.0539048165,
  0.1148343533,
  0.0557029285,
  -0.1346054971,
  0.0756406337,
  0.1429026127,
  -0.0771950334,
  -0.0017605424,
  -0.1092553958,
  0.0860188976,
  -0.0260452237,
  -0.2512567639,
  -0.1099327877,
  0.0864083096,
  -0.0951557904,
  -0.0508181229,
  -0.1021407768,
  -0.1019067392,
  0.103467688,
  -0.095251292,
  0.1451020241,
  -0.0996131077,
  0.0111184614,
  0.1327464581,
  0.0853461102,
  0.0843517929,
  -0.2181839943,
  0.0725586936,
  -0.0068759676,
  -0.0028136075,
  -0.0248903055,
  0.1121691093,
  -0.0144790513,
  -0.1914690137,
  -0.066657871,
  -0.1102516949,
  0.0385337435,
  0.127661258,
  0.069056578,
  1.1052669287,
  0.6730465293,
  0.1553273499,
  -0.0041204891,
  -0.034063492,
  0.0175159983,
  -0.0287432913,
  0.0154504441,
  0.1422827393,
  -0.0785864741,
  0.0517769456,
  -0.0311446469,
  0.1134000644,
  -0.0230390988,
  0.0814435631,
  0.0129948277,
  0.0672965944,
  0.0043415413,
  -0.0219257399,
  -0.0062197628,
  -0.07958287,
  -0.1203824878,
  0.0456716083,
  -0.0130782397,
  0.1683869809,
  0.0894570798,
  0.2753022909,
  0.0757117346,
  0.039683219,
  -0.1702937484,
  0.0504928194,
  -0.0327929147,
  0.0333393626,
  -0.141793564,
  -0.0584025159,
  -0.1974290758,
  0.0514577068,
  0.1139465868,
  0.1599077135,
  0.0888829455,
  0.0870998129,
  0.0594617575,
  0.0370732099,
  0.0636662021,
  0.1612534523,
  0.0548249483,
  0.0573831201,
  0.0191210378,
  0.245421201,
  0.1006545648,
  0.0732159391,
  0.10489849,
  -0.1199409515,
  0.0903226361,
  0.0287905615,
  -0.176620394,
  0.0611627251,
  -0.1037327722,
  0.2603441775,
  -0.1031135619,
  0.1592669487,
  0.0888199061,
  -0.0793901309,
  -0.0654651374,
  0.0450211354,
  0.0241930801,
  -0.007452067,
  -0.2017166764,
  0.1868059039,
  -0.1758924872,
  -0.003038432,
  0.2025848031,
  -0.0660883784,
  -0.0408989824,
  -0.0465735532,
  -0.0408071578,
  -0.2723757625,
  0.0743314922,
  0.0721130669,
  -0.019822076,
  0.0447278097,
  0.1787803918,
  0.0282460134,
  -0.1049268469,
  0.0843596756,
  0.0537206568,
  -0.0262417197,
  0.0661243796,
  -0.1502753794,
  0.0958147496,
  -0.0520361215,
  0.0519954413,
  0.1013314351,
  -0.1300710291,
  0.1949228048,
  -0.1398026645,
  0.3870576322,
  0.0092985947,
  0.0368076935,
  0.0207030792,
  -0.0037374618,
  0.1075115427,
  -0.205033794,
  0.0641286075,
  -0.0260393806,
  -0.0077999188,
  0.1024135873,
  -0.0363089032,
  -0.1488530785,
  -0.0803706944,
  -0.1655054986,
  0.0007052391,
  0.0745701641,
  0.0775157735,
  -0.0652702302,
  0.0348699167,
  0.0209362321,
  -0.0780564323,
  0.1502180398,
  0.2285879552,
  0.1376377344,
  0.0059235026,
  -0.1869433373,
  -1.3074643612,
  0.04688688,
  0.080967471,
  0.0718560964,
  0.1023051813,
  -0.088052094,
  0.0438034311,
  -0.1454544812,
  0.0535444915,
  -0.07695245,
  0.0336101502,
  -0.0408617407,
  0.0320359804,
  -0.0383620188,
  0.0925562009,
  -0.118200399,
  0.0362448692,
  0.0714500546,
  0.0622732118,
  0.0465451591,
  -0.057388451,
  0.0010043622,
  0.0638799667,
  0.0516397394,
  0.1452967077,
  -0.118252486,
  0.0877513289,
  0.0165518802,
  0.0052690459,
  0.0048448886,
  -0.0230245478,
  0.0866391137,
  -0.109635137,
  -0.00741923,
  -0.0801528916,
  0.1249878183,
  -0.0001439973,
  -0.1748093963,
  -0.1492710859,
  0.1342131644,
  0.0935371146,
  0.401440531,
  0.1814621091,
  -0.0147033706,
  -0.0686303005,
  0.0680466816,
  -0.0209645834,
  0.0160954259,
  0.0422619879,
  0.028011756,
  -0.077001676,
  0.0790197179,
  -0.0036572393,
  0.11454162,
  0.0342693999,
  0.0390196703,
  -0.0341928713,
  0.024648929,
  -0.085674718,
  0.0807005912,
  -0.0275020897,
  0.0399341099,
  0.0119521599,
  0.1305087805,
  -0.1810209006,
  -0.1561601907,
  -0.0055961157,
  -0.0453813151,
  -0.0688664019,
  0.0361487195,
  0.0269550886,
  0.0048434902,
  -0.1002990529,
  0.097131528,
  0.024636481,
  0.0345667414,
  0.0150481518,
  0.0948291719,
  0.0159094688,
  0.0934354588,
  0.0951280445,
  0.046995379,
  0.1029020026,
  -0.0643434823,
  0.0410914496,
  -0.1218389198,
  0.0939214304,
  -0.1089198217,
  0.1476395577,
  0.048733525,
  0.0641567484,
  0.2876037061,
  0.0092401356,
  0.0510885753,
  -0.04378438,
  -0.1357870251,
  -0.0091311159,
  -0.1232788712,
  0.851852119,
  -0.0674200207,
  0.1058506519,
  -0.1045529544,
  0.0794796273,
  0.0303285215,
  0.1023694053,
  -0.0844451636,
  0.3161705136,
  -0.0554833189,
  -0.0893529132,
  -0.0488164127,
  0.0258179531,
  -0.0618945844,
  -0.072416991,
  0.1290574223,
  0.0175654124,
  -0.0153159462,
  -0.0336306915,
  -0.1743782461,
  0.0774067864,
  0.1057144031,
  0.2001292855,
  0.2226989418,
  0.0798727274,
  0.0788127482,
  -0.1434611976,
  -0.0593538508,
  0.0722552612,
  -0.2501288652,
  0.0352802463,
  -0.0081097931,
  0.0618558228,
  0.0906469673,
  0.3281775415,
  0.0928721279,
  -0.2128181756,
  11.2996578217,
  0.0212572291,
  0.0016471165,
  0.1148004159,
  0.1006458476,
  0.1087899655,
  0.2041483223,
  0.0398358367,
  0.0398265831,
  0.2063065767,
  -0.01186777,
  -0.0184776578,
  -0.0931172892,
  0.0498976,
  -0.0080507854,
  0.0503168479,
  0.0211676396,
  0.0983515605,
  0.0762986317,
  0.0090647601,
  -0.0486347117,
  0.223896265,
  0.0465577096,
  0.3122341633,
  -0.0404199474,
  0.0843321607,
  -0.0725250244,
  0.1448260248,
  -0.1200151592,
  0.0791980177,
  0.1153125763,
  0.0356450379,
  -0.0766804516,
  -0.0214344002,
  -0.0358744115,
  0.0204344224,
  0.437769264,
  0.0642646626,
  0.0367122963,
  0.0062231957,
  0.0998518169,
  -0.1077376157,
  0.0704788119,
  0.1009747535,
  0.0835452527,
  -0.0677503645,
  -0.0546503924,
  0.0037453508,
  0.0302925501,
  -0.0205930285,
  0.0097550768,
  0.028255837,
  -0.0059921425,
  -0.1694397926,
  0.0488334671,
  0.0066510816,
  -0.0077140024,
  0.147313565,
  0.0294271689,
  0.1259708852,
  0.0645448864,
  0.0440440141,
  0.0613335781,
  0.0904825926,
  -0.0065316609,
  0.1687195748,
  0.0180542059,
  0.2867661119,
  -0.2568666041,
  0.0377105363,
  -0.0124689657,
  0.0035386079,
  0.0512589924,
  -0.0288750846,
  -0.0070102881,
  -0.0453008525,
  0.478161931,
  0.0119796852,
  -0.0202090386,
  0.1999881417,
  0.0992254913,
  0.0563179031,
  0.1428704262,
  -0.1011903137,
  0.2925933003,
  0.1721806675,
  -0.0159230009,
  0.0717354938,
  -0.0245129168,
  0.0566490516,
  0.0528053939,
  0.1720711887,
  0.1468147039,
  0.0489609949,
  -0.0952603519,
  0.0772197172,
  -0.1529533863,
  -0.2008484155,
  0.0443519577,
  0.1337860972,
  0.0861168504,
  0.2134817839,
  -0.0323578455,
  0.0704743117,
  0.0119040571,
  -0.0552643538,
  0.0271462724,
  0.0813166201,
  0.1043904945,
  -0.0392647646,
  -0.0648261979,
  -0.0161588676,
  -0.0552538931,
  0.0518941805,
  0.0974928066,
  -0.0947819948,
  -0.0928331837,
  0.0471783243,
  0.1102410704,
  -0.1577838361,
  -0.0425429717,
  0.0279673543,
  -0.0006894711,
  0.0871282592,
  0.0253058411,
  0.0450893976,
  0.0686616749,
  0.0076495977,
  -0.0232355837,
  0.0757542774,
  -0.1539224088,
  0.1239147931,
  0.1533530504,
  -0.0452632643,
  0.1984546483,
  0.0399239548,
  -0.0403768122,
  0.0630296022,
  0.1968033761,
  0.163007021,
  -0.1097871587,
  0.0554625578,
  0.1063126698,
  -0.2225376815,
  -0.0856785253,
  -0.003957734,
  0.1013703868,
  -0.104450874,
  0.1796831787,
  -0.0200866852,
  0.2142222673,
  0.0831216723,
  -0.0479545444,
  0.1515873522,
  -0.1620578617,
  0.1561275721,
  0.1149353459,
  0.2037175596,
  0.0998010412,
  0.0632424206,
  0.1147639453,
  -0.0455149747,
  -0.025139045,
  -0.105922468,
  0.1458580941,
  -0.0101329768,
  0.0809872895,
  0.0860034898,
  0.0067670783,
  -0.0781095922,
  0.0425613634,
  0.0215244256,
  -0.0856720284,
  -0.0032977546,
  0.1333266199,
  -0.0131407483,
  0.2795410752,
  -0.0376711078,
  0.0101755327,
  0.1613402963]}

In [4]:
len(all_chunks_dict)

65306

In [5]:
# Connect to the database
db_session = get_db_session(db_url)

try:
    # Insert all chunks at once
    inserted = populate_doc_chunks_from_dict(
        chunks_list=all_chunks_dict,
        db_session=db_session,
        delete_existing=True,
        batch_size=1000
    )
    print(f"Inserted {inserted} chunks into the database")
finally:
    db_session.close()

Inserted 65306 chunks into the database

### Create vector similarity index

In [8]:
engine = create_engine(db_url)

with engine.connect() as conn:
        # Create the pgvector extension if it doesn't exist
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
        
        # Convert column type from ARRAY(Float) to vector
        # Only needed once after initial data load
        conn.execute(text("""
            ALTER TABLE doc_chunks 
            ALTER COLUMN embedding TYPE vector(768)
            USING embedding::vector(768);
        """))
        # Create an index on the embedding column for faster similarity search
        # The ivfflat index type is good for cosine similarity searches
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS chunks_embedding_idx 
            ON doc_chunks 
            USING ivfflat (embedding vector_cosine_ops)
            WITH (lists = 100);
        """))
        conn.commit()

Check the number of chunks corresponding to each doc_id in the database.

In [9]:
doc_id = "albania_english_20220801"
db_session = get_db_session(db_url)

try:
    count = count_chunks_for_doc(doc_id, db_session)
    print(f"Document {doc_id} is related to {count} rows in the doc_chunks table.")
finally:
    db_session.close()

Document albania_english_20220801 is related to 1071 rows in the doc_chunks table.